name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
      with:
        # Version to use. E.g. 2.2.104
        version: '3.0.100'
    - name: Build with dotnet
      run: dotnet build --configuration Release
